### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by lukejkelly** [traitlab-mcmc/TraitLab#2]
- [x] Fix experiment and analysis GUIs across platforms
- [x] Update system to run batch input files
- [x] Re-check initial beta values when true value present
- [x] Update README
- [x] Tidy up main folder
- [x] Dropping taxa from analyses
---
- [x] Check batchIN against GUI
---
* Error if we attempt to start from tree in output file then switch to using the true tree and attempt to view it.
---
- [x] Set RNG seed before any other initialisation functions use it
- [x] Arguments to batchTraitLab
